const code=(sql,label='SQL')=>`<div class="code-block"><div class="code-label"><span>${label}</span><button data-copy>Copy query</button></div><pre><code>${sql.replace(/</g,'&lt;')}</code></pre></div>`;
const table=(heads,rows,numeric=[])=>`<table class="data-table"><thead><tr>${heads.map((h,i)=>`<th class="${numeric.includes(i)?'num':''}">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${numeric.includes(i)?'num':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const quiz=(question,answers,correct,why)=>`<section class="quiz" data-correct="${correct}" data-why="${why}"><span class="quiz-tag">KNOWLEDGE CHECK · +20 XP</span><h3>${question}</h3><div class="answers">${answers.map((a,i)=>`<button class="answer" data-answer="${i}">${a}</button>`).join('')}</div><div class="feedback"></div></section>`;
const lesson=(title,time,body)=>({title,time,body});

let segments=[
 {title:'MySQL Basics',desc:'Read tables, select columns, filter and sort rows.',lessons:[
  lesson('Think in tables',5,`<p class="eyebrow">THE MENTAL MODEL</p><h2>A database is an organized collection of facts.</h2><p>MySQL stores related data in <strong>tables</strong>. A table is a grid: columns define what kind of fact is stored; rows are individual records.</p><div class="diagram">coffee_shop DATABASE<br>│<br>├── products TABLE<br>│   ├── product_id COLUMN<br>│   ├── product_name COLUMN<br>│   └── price COLUMN<br>└── orders TABLE</div>${table(['Term','Analyst meaning'],[['Database','Container for related tables'],['Table','Structured rows and columns'],['Column','One measurable field or attribute'],['Row','One observation or record'],['Query','A question written in SQL']])}<div class="insight"><b>01</b><div><strong>Analyst habit</strong><br>Before querying, identify the unit of one row. In <code>orders</code>, one row is one product order line—not necessarily one entire customer transaction.</div></div>${quiz('Which object contains rows and columns?',['A database','A table','A query'],1,'A table is the grid that holds rows and columns.')}`),
  lesson('SELECT and FROM',6,`<p class="eyebrow">ASKING YOUR FIRST QUESTION</p><h2>Choose what to show, then where it comes from.</h2><p><code>SELECT</code> names the columns in your result. <code>FROM</code> names the source table. SQL statements end with a semicolon.</p>${code(`SELECT product_name, price\nFROM products;`)}<p>The asterisk means “all columns.” It is useful while exploring, but analysts usually name only the fields needed.</p>${code(`SELECT *\nFROM products;`)}${table(['product_name','price'],[['Iced Latte','2.750'],['Cold Brew','3.000'],['Croissant','1.500']],[1])}${quiz('What does FROM products mean?',['Only show product names','Read rows from the products table','Create a products table'],1,'FROM identifies the table that supplies the data.')}`),
  lesson('Filter with WHERE',7,`<p class="eyebrow">REDUCE THE ROWS</p><h2>WHERE tests every row against a condition.</h2><p>Only rows where the condition is true survive. Text and dates use quotes; numeric values do not.</p>${code(`SELECT product_name, price\nFROM products\nWHERE category = 'Coffee';`)}${table(['Operator','Meaning','Example'],[['=','equal','price = 3'],['>','greater than','price > 2'],['>=','at least','price >= 2'],['<','less than','price < 2'],['<>','not equal','category <> \'Coffee\'']])}<div class="callout"><strong>Order matters</strong>Write <code>SELECT → FROM → WHERE</code>. SQL keywords are commonly uppercase for readability, though MySQL accepts lowercase.</div>${quiz('Which condition finds products costing more than 2?',[`WHERE price > '2'`,`WHERE price > 2`,`WHERE price = > 2`],1,'Numbers do not need quotes, and the greater-than operator is >.')}`),
  lesson('Sort and limit',6,`<p class="eyebrow">RANK THE RESULT</p><h2>ORDER BY turns a list into a ranking.</h2><p><code>ASC</code> sorts smallest to largest and is the default. <code>DESC</code> sorts largest to smallest. <code>LIMIT</code> keeps a specified number of rows.</p>${code(`SELECT product_name, price\nFROM products\nORDER BY price DESC\nLIMIT 1;`)}${table(['product_name','price'],[['Cold Brew','3.000']],[1])}<div class="insight"><b>?</b><div><strong>Business answer</strong><br>Cold Brew is the most expensive product in the current catalog at 3.000.</div></div>${quiz('How do you return the three cheapest products?',['ORDER BY price DESC LIMIT 3','ORDER BY price ASC LIMIT 3','LIMIT 3 ORDER BY price'],1,'Ascending price places the cheapest first; LIMIT 3 keeps three rows.')}`)
 ]},
 {title:'Build the Database',desc:'Create the schema and load clean product data.',lessons:[
  lesson('Create and select a database',5,`<p class="eyebrow">BUILD THE CONTAINER</p><h2>Create a safe workspace for your tables.</h2><p><code>IF NOT EXISTS</code> prevents an error if the database is already present. <code>USE</code> selects it for the statements that follow.</p>${code(`CREATE DATABASE IF NOT EXISTS coffee_shop;\n\nUSE coffee_shop;`)}<div class="diagram">MySQL server<br>└── coffee_shop  ← active database<br>    ├── products<br>    └── orders</div>${quiz('Why run USE coffee_shop?',['To delete it','To select it as the active database','To display every table'],1,'USE sets the database context for later statements.')}`),
  lesson('Design the products table',8,`<p class="eyebrow">DEFINE THE STRUCTURE</p><h2>Data types are rules for each column.</h2><p>A table definition protects data quality. A price should behave like a number; a name should behave like text.</p>${code(`DROP TABLE IF EXISTS products;\n\nCREATE TABLE products (\n    product_id INT,\n    product_name VARCHAR(100),\n    category VARCHAR(50),\n    price DECIMAL(6,3)\n);`)}${table(['Type','Stores','Example'],[['INT','Whole numbers','6'],['VARCHAR(100)','Text up to 100 characters',`'Iced Latte'`],['DECIMAL(6,3)','6 total digits, 3 after decimal','2.750'],['DATE','Calendar dates',`'2026-06-20'`]])}<div class="callout"><strong>DECIMAL(6,3)</strong>The first number is total digits; the second is digits after the decimal. It can hold values up to 999.999.</div>${quiz('Which type is safest for a monetary price in this course?',['INT','DATE','DECIMAL(6,3)'],2,'DECIMAL stores exact fixed-point values suitable for prices.')}`),
  lesson('Insert product rows',7,`<p class="eyebrow">LOAD THE FACTS</p><h2>INSERT maps values to named columns.</h2><p>Each parenthesized group is one row. Its values must be in the same order as the listed columns.</p>${code(`INSERT INTO products (product_id, product_name, category, price)\nVALUES\n    (1, 'Iced Latte', 'Coffee', 2.750),\n    (2, 'Cold Brew', 'Coffee', 3.000),\n    (3, 'Croissant', 'Pastry', 1.500),\n    (4, 'Brownie', 'Dessert', 1.750),\n    (5, 'Matcha Latte', 'Tea', 2.900),\n    (6, 'Americano', 'Coffee', 1.250);`)}<p>Verify both structure and data:</p>${code(`DESCRIBE products;\nSELECT * FROM products;`)}${quiz('What must match in an INSERT statement?',['The values and listed column order','All text and numbers must have quotes','Rows must be alphabetic'],0,'Each value position maps directly to the same position in the column list.')}`)
 ]},
 {title:'Orders & KPIs',desc:'Calculate revenue, aggregates, filters and dates.',lessons:[
  lesson('The orders dataset',7,`<p class="eyebrow">FROM CATALOG TO BEHAVIOR</p><h2>Products show what can sell. Orders show what did sell.</h2><p>The analytical grain is one order row. <code>quantity</code> says how many units that row represents.</p>${table(['order_id','product_name','category','quantity','unit_price','order_date'],[['1','Iced Latte','Coffee','2','2.750','2026-06-20'],['2','Cold Brew','Coffee','1','3.000','2026-06-20'],['3','Croissant','Pastry','3','1.500','2026-06-20'],['4','Brownie','Dessert','2','1.750','2026-06-21'],['…','…','…','…','…','…'],['10','Iced Latte','Coffee','3','2.750','2026-06-23']],[0,3,4])}<div class="callout"><strong>Date format</strong>MySQL date literals use <code>'YYYY-MM-DD'</code>: largest time unit to smallest.</div>${quiz('What is the unit of one row in this orders table?',['One shop day','One product order line','One individual item'],1,'Each row is a product order line; quantity may represent several items.')}`),
  lesson('Calculated columns',6,`<p class="eyebrow">ROW-LEVEL MATH</p><h2>Revenue = quantity × unit price.</h2><p>SQL can calculate a new value for every row. <code>AS revenue</code> supplies a readable temporary alias; it does not alter the stored table.</p>${code(`SELECT\n    product_name,\n    quantity,\n    unit_price,\n    quantity * unit_price AS revenue\nFROM orders;`)}${table(['product_name','quantity','unit_price','revenue'],[['Iced Latte','2','2.750','5.500'],['Cold Brew','1','3.000','3.000'],['Croissant','3','1.500','4.500']],[1,2,3])}${quiz('What is revenue for 4 Americanos at 1.250 each?',['3.250','4.000','5.000'],2,'4 × 1.250 = 5.000.')}`),
  lesson('Aggregate functions & KPIs',9,`<p class="eyebrow">MANY ROWS → ONE ANSWER</p><h2>Aggregates compress detail into metrics.</h2>${table(['Function','Question it answers'],[['COUNT(*)','How many rows?'],['SUM(quantity)','How many items?'],['AVG(expression)','What is the mean?'],['MIN(expression)','What is the smallest?'],['MAX(expression)','What is the largest?']])}${code(`SELECT\n    COUNT(*) AS total_order_rows,\n    SUM(quantity) AS total_items_sold,\n    SUM(quantity * unit_price) AS total_revenue,\n    ROUND(AVG(quantity * unit_price), 3) AS avg_order_row_revenue\nFROM orders;`)}${table(['total_order_rows','total_items_sold','total_revenue','avg_order_row_revenue'],[['10','21','45.800','4.580']],[0,1,2,3])}<div class="insight"><b>Σ</b><div><strong>Check the math</strong><br>Average order-row revenue = 45.800 ÷ 10 rows = 4.580.</div></div>${quiz('Why are total_order_rows and total_items_sold different?',['COUNT counts rows; SUM(quantity) counts units','COUNT rounds down','SUM ignores coffee'],0,'One row can contain multiple units, so rows and items measure different things.')}`),
  lesson('Filter analytical questions',9,`<p class="eyebrow">CONTROL THE INPUT</p><h2>WHERE filters before the metric is calculated.</h2>${code(`SELECT SUM(quantity * unit_price) AS coffee_revenue\nFROM orders\nWHERE category = 'Coffee';`)}${table(['coffee_revenue'],[['30.500']],[0])}<p>Combine conditions with <code>AND</code>. Use <code>IN</code> when one field may match several values.</p>${code(`SELECT SUM(quantity * unit_price) AS coffee_revenue_june_20_to_22\nFROM orders\nWHERE category = 'Coffee'\n  AND order_date BETWEEN '2026-06-20' AND '2026-06-22';`)}${table(['coffee_revenue_june_20_to_22'],[['22.250']],[0])}<div class="callout"><strong>BETWEEN is inclusive</strong>Both June 20 and June 22 are included in this date filter.</div>${quiz('Which rows does BETWEEN June 20 AND June 22 include?',['Only June 21','June 20, 21, and 22','June 20 and 21 only'],1,'BETWEEN includes both endpoints.')}`)
 ]},
 {title:'GROUP BY',desc:'Build product, category, and daily performance reports.',lessons:[
  lesson('Why GROUP BY exists',7,`<p class="eyebrow">SEGMENT 4 · SUMMARIZE</p><h2>Turn one big pile into meaningful buckets.</h2><p>Without <code>GROUP BY</code>, an aggregate gives one answer for the whole table. Grouping calculates a separate answer for every distinct value.</p><div class="diagram">GROUP BY product_name<br><br>Iced Latte bucket     Cold Brew bucket      Croissant bucket<br>├── order 1           ├── order 2           ├── order 3<br>├── order 5           └── order 8           └── order 9<br>└── order 10<br>     ↓ SUM()                ↓ SUM()               ↓ SUM()</div>${code(`SELECT\n    category,\n    SUM(quantity * unit_price) AS revenue\nFROM orders\nGROUP BY category;`)}${table(['category','revenue'],[['Coffee','30.500'],['Pastry','6.000'],['Dessert','3.500'],['Tea','5.800']],[1])}${quiz('How many result rows should GROUP BY category return here?',['1','4','10'],1,'There are four distinct category buckets, so the result has four rows.')}`),
  lesson('Revenue by product',8,`<p class="eyebrow">PRODUCT PERFORMANCE</p><h2>Calculate inside each product bucket.</h2>${code(`SELECT\n    product_name,\n    SUM(quantity * unit_price) AS revenue\nFROM orders\nGROUP BY product_name\nORDER BY revenue DESC;`)}${table(['product_name','revenue'],[['Iced Latte','16.500'],['Cold Brew','9.000'],['Croissant','6.000'],['Matcha Latte','5.800'],['Americano','5.000'],['Brownie','3.500']],[1])}<h3>Audit the Iced Latte result</h3>${table(['order_id','quantity','unit_price','row revenue'],[['1','2','2.750','5.500'],['5','1','2.750','2.750'],['10','3','2.750','8.250'],['','', '<strong>Total</strong>','<strong>16.500</strong>']],[0,1,2,3])}<div class="insight"><b>#1</b><div><strong>Iced Latte leads revenue</strong><br>Add <code>LIMIT 1</code> after descending sort to return only the winner.</div></div>${quiz('Which clause creates one bucket per product?',['ORDER BY product_name','GROUP BY product_name','WHERE product_name'],1,'GROUP BY creates a group for each distinct product name.')}`),
  lesson('Items sold vs. revenue',8,`<p class="eyebrow">TWO METRICS, TWO STORIES</p><h2>Volume and money are not interchangeable.</h2>${code(`SELECT\n    product_name,\n    SUM(quantity) AS items_sold,\n    SUM(quantity * unit_price) AS revenue\nFROM orders\nGROUP BY product_name\nORDER BY items_sold DESC;`)}${table(['product_name','items_sold','revenue'],[['Iced Latte','6','16.500'],['Americano','4','5.000'],['Croissant','4','6.000'],['Cold Brew','3','9.000'],['Brownie','2','3.500'],['Matcha Latte','2','5.800']],[1,2])}<div class="callout"><strong>Analyst interpretation</strong>Americano sold 4 units and Matcha Latte sold only 2, yet Matcha generated more revenue (5.800 vs 5.000) because its unit price is higher.</div>${quiz('A product can rank higher in revenue but lower in units because…',['GROUP BY changes prices','Its unit price is higher','COUNT adds quantities'],1,'Revenue combines volume and price, so a higher price can offset fewer units.')}`),
  lesson('Orders, items & revenue by day',10,`<p class="eyebrow">TIME SERIES BASICS</p><h2>One day can win one KPI and lose another.</h2>${code(`SELECT\n    order_date,\n    COUNT(*) AS order_rows,\n    SUM(quantity) AS items_sold,\n    SUM(quantity * unit_price) AS revenue\nFROM orders\nGROUP BY order_date\nORDER BY order_date;`)}${table(['order_date','order_rows','items_sold','revenue'],[['2026-06-20','3','6','13.000'],['2026-06-21','3','5','12.050'],['2026-06-22','3','7','12.500'],['2026-06-23','1','3','8.250']],[1,2,3])}<div class="insight"><b>↗</b><div><strong>Read across metrics</strong><br>June 22 sold the most items (7), but June 20 earned the most revenue (13.000). More items do not guarantee more money.</div></div>${code(`SELECT order_date,\n       SUM(quantity * unit_price) AS revenue\nFROM orders\nGROUP BY order_date\nORDER BY revenue DESC\nLIMIT 1;`,'BEST REVENUE DAY')}${quiz('Which date sold the most items?',['2026-06-20','2026-06-22','2026-06-23'],1,'June 22 has SUM(quantity) = 7, the highest daily item count.')}`),
  lesson('Group by multiple columns',9,`<p class="eyebrow">MORE SPECIFIC BUCKETS</p><h2>Each added grouping column refines the grain.</h2><p>If you select a non-aggregated field, it normally belongs in <code>GROUP BY</code>. Grouping by category alone cannot safely display product_name because one category contains several products.</p><div class="diagram">GROUP BY category, product_name<br><br>Coffee<br>├── Iced Latte  → one result row<br>├── Cold Brew   → one result row<br>└── Americano   → one result row<br><br>Pastry<br>└── Croissant   → one result row</div>${code(`SELECT\n    category,\n    product_name,\n    SUM(quantity) AS items_sold\nFROM orders\nGROUP BY category, product_name\nORDER BY category, items_sold DESC;`)}${table(['category','product_name','items_sold'],[['Coffee','Iced Latte','6'],['Coffee','Americano','4'],['Coffee','Cold Brew','3'],['Dessert','Brownie','2'],['Pastry','Croissant','4'],['Tea','Matcha Latte','2']],[2])}${quiz('Why is selecting product_name while grouping only by category unsafe?',['Product names are too long','A category contains multiple product names','SUM cannot use text'],1,'MySQL would not have one unambiguous product name for the category result row.')}`),
  lesson('WHERE + GROUP BY report',10,`<p class="eyebrow">FILTER, THEN SUMMARIZE</p><h2>SQL follows a logical pipeline.</h2><div class="diagram">FROM orders<br>   ↓ choose source rows<br>WHERE order_date BETWEEN ...<br>   ↓ discard non-matching rows<br>GROUP BY category<br>   ↓ form category buckets<br>SELECT SUM(...)<br>   ↓ calculate each result<br>ORDER BY revenue DESC<br>   ↓ rank the rows<br>LIMIT ...</div>${code(`SELECT\n    category,\n    COUNT(*) AS order_rows,\n    SUM(quantity) AS items_sold,\n    SUM(quantity * unit_price) AS revenue,\n    ROUND(AVG(quantity * unit_price), 3) AS avg_order_row_revenue\nFROM orders\nWHERE order_date BETWEEN '2026-06-20' AND '2026-06-22'\nGROUP BY category\nORDER BY revenue DESC;`)}${table(['category','order_rows','items_sold','revenue','avg row revenue'],[['Coffee','5','10','22.250','4.450'],['Pastry','2','4','6.000','3.000'],['Tea','1','2','5.800','5.800'],['Dessert','1','2','3.500','3.500']],[1,2,3,4])}<div class="callout"><strong>Next: HAVING</strong><code>WHERE</code> filters detail rows before grouping. Segment 5 will introduce <code>HAVING</code>, which filters completed groups—for example, only categories with revenue above 5.</div>${quiz('When does WHERE act relative to GROUP BY?',['Before grouping','After grouping','Only after ORDER BY'],0,'WHERE controls which detail rows enter the groups.')}`)
 ]}
];

if (window.SOURCE_SEGMENTS?.length) segments = window.SOURCE_SEGMENTS;

const state=JSON.parse(localStorage.getItem('qg-progress')||'{"segment":0,"lesson":0,"complete":[],"quizzes":[],"theme":"dark"}');
const deepLink = new URLSearchParams(location.search);
if (deepLink.has('segment')) state.segment = Math.max(0, Math.min(segments.length - 1, Number(deepLink.get('segment')) || 0));
if (deepLink.has('lesson')) state.lesson = Math.max(0, Math.min(segments[state.segment].lessons.length - 1, Number(deepLink.get('lesson')) || 0));
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const lessonId=(s=state.segment,l=state.lesson)=>`${s}-${l}`;
const escapeHTML=value=>value.replace(/[&<>]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[char]));
function save(){localStorage.setItem('qg-progress',JSON.stringify(state));renderStats()}
function enterLessonMode(){document.body.classList.add('lesson-mode');document.body.classList.remove('nav-open');window.scrollTo({top:0,behavior:'smooth'})}
function leaveLessonMode(){document.body.classList.remove('lesson-mode','nav-open');window.scrollTo({top:0,behavior:'smooth'})}
function renderRoadmap(){
 $('#roadmapList').innerHTML=segments.map((s,i)=>{const done=s.lessons.filter((_,j)=>state.complete.includes(`${i}-${j}`)).length;return `<button class="roadmap-card ${i===state.segment?'active':''} ${done===s.lessons.length?'done':''}" data-segment="${i}"><small>CHAPTER ${String(i+1).padStart(2,'0')}</small><h3>${s.title}</h3><p>${s.desc}</p><span class="card-progress">${done}/${s.lessons.length} SECTIONS COMPLETE</span></button>`}).join('');
 $$('.roadmap-card').forEach(b=>b.onclick=()=>{state.segment=+b.dataset.segment;state.lesson=0;save();render();enterLessonMode()});
}
function renderTabs(){
 const active=segments[state.segment];$('#segmentKicker').textContent=`CHAPTER ${state.segment+1}`;$('#segmentTitle').textContent=active.title;
 $('#lessonTabs').innerHTML=`<button class="course-overview-link">⌂ <span>Course overview</span></button>`+segments.map((segment,segmentIndex)=>{const isActive=segmentIndex===state.segment,done=segment.lessons.filter((_,lessonIndex)=>state.complete.includes(`${segmentIndex}-${lessonIndex}`)).length;return `<section class="nav-group ${isActive?'active':''}"><button class="segment-toggle" data-segment="${segmentIndex}" aria-expanded="${isActive}"><span class="segment-index">${String(segmentIndex+1).padStart(2,'0')}</span><span>${segment.title}</span><small>${done}/${segment.lessons.length}</small><span class="chevron">›</span></button>${isActive?`<div class="segment-lessons">${segment.lessons.map((lessonTitle,lessonIndex)=>`<button class="tab-btn ${lessonIndex===state.lesson?'active':''} ${state.complete.includes(`${segmentIndex}-${lessonIndex}`)?'done':''}" data-lesson="${lessonIndex}"><span>${String(lessonIndex+1).padStart(2,'0')}</span>${lessonTitle.title}</button>`).join('')}</div>`:''}</section>`}).join('');
 $('.course-overview-link').onclick=leaveLessonMode;
 $$('.segment-toggle').forEach(button=>button.onclick=()=>{const next=+button.dataset.segment;if(next!==state.segment){state.segment=next;state.lesson=0;save();render()} });
 $$('.tab-btn').forEach(button=>button.onclick=()=>{state.lesson=+button.dataset.lesson;save();render();enterLessonMode()});
}
function highlightSQL(){
 const pattern=/(--[^\n]*|'(?:''|[^'])*'|\b(?:SELECT|FROM|WHERE|GROUP|BY|HAVING|ORDER|ASC|DESC|LIMIT|AS|DISTINCT|JOIN|INNER|LEFT|RIGHT|CROSS|ON|AND|OR|NOT|IN|IS|NULL|BETWEEN|LIKE|WITH|OVER|PARTITION|ROWS|RANGE|UNBOUNDED|PRECEDING|CURRENT|ROW|CASE|WHEN|THEN|ELSE|END|CREATE|DATABASE|TABLE|VIEW|INDEX|ALTER|ADD|CONSTRAINT|PRIMARY|FOREIGN|KEY|REFERENCES|INSERT|INTO|VALUES|UPDATE|SET|DELETE|DROP|USE|DESCRIBE|EXPLAIN|SHOW|START|TRANSACTION|COMMIT|ROLLBACK|IF|EXISTS|AUTO_INCREMENT|DEFAULT)\b|\b(?:COUNT|SUM|AVG|MIN|MAX|ROUND|COALESCE|TRIM|LOWER|UPPER|CONCAT|DATE_FORMAT|YEAR|MONTH|DAY|DAYNAME|DATEDIFF|ROW_NUMBER|RANK|DENSE_RANK|LAG|LEAD|NULLIF)\b(?=\s*\()|\b\d+(?:\.\d+)?\b)/gi;
 $$('.code-block pre code').forEach(block=>{const escaped=escapeHTML(block.textContent);block.innerHTML=escaped.replace(pattern,token=>{const upper=token.toUpperCase();let type='number';if(token.startsWith('--'))type='comment';else if(token.startsWith("'"))type='string';else if(/^(COUNT|SUM|AVG|MIN|MAX|ROUND|COALESCE|TRIM|LOWER|UPPER|CONCAT|DATE_FORMAT|YEAR|MONTH|DAY|DAYNAME|DATEDIFF|ROW_NUMBER|RANK|DENSE_RANK|LAG|LEAD|NULLIF)$/i.test(upper))type='function';else if(/^[A-Z_]+$/i.test(token))type='keyword';return `<span class="sql-${type}">${token}</span>`})});
}
function renderToc(){
 const headings=$$('#lessonContent h2, #lessonContent h3').filter(heading=>!heading.closest('details'));
 headings.forEach((heading,index)=>heading.id=`lesson-heading-${index}`);
 $('#lessonToc').innerHTML=headings.slice(0,18).map(heading=>`<a class="toc-${heading.tagName.toLowerCase()}" href="#${heading.id}">${heading.textContent}</a>`).join('')||'<span class="toc-empty">Single-topic lesson</span>';
}
function renderLesson(){
 const s=segments[state.segment],l=s.lessons[state.lesson],id=lessonId();$('#lessonNumber').textContent=String(state.lesson+1).padStart(2,'0');$('#readingTime').textContent=`${l.time} MIN SECTION`;$('#lessonContent').innerHTML=l.body;$('#breadcrumbSegment').textContent=`Chapter ${state.segment+1} · ${s.title}`;$('#breadcrumbLesson').textContent=l.title;const done=state.complete.includes(id);$('#completeLesson').classList.toggle('done',done);$('#completeLesson').innerHTML=done?'Completed <span>✓</span>':'Mark complete <span>✓</span>';$('#prevLesson').disabled=state.segment===0&&state.lesson===0;$('#nextLesson').innerHTML=state.segment===segments.length-1&&state.lesson===s.lessons.length-1?'Finish course <span>✓</span>':'Next section <span>→</span>';
 renderToc();highlightSQL();
 $$('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.closest('.code-block').querySelector('code').textContent);toast('Query copied')});
 $$('.quiz').forEach((q,index)=>{
   const quizId=`${id}-q${index}`;q.dataset.quizId=quizId;
   if(state.quizzes.includes(quizId)){
     const correct=+q.dataset.correct;q.querySelectorAll('.answer').forEach(x=>x.disabled=true);
     q.querySelector(`[data-answer="${correct}"]`).classList.add('correct');
     q.querySelector('.feedback').textContent='Correct. '+q.dataset.why;
   }
 });
 $$('.answer').forEach(b=>b.onclick=answerQuiz);
}
function answerQuiz(e){const b=e.currentTarget,q=b.closest('.quiz'),correct=+q.dataset.correct,chosen=+b.dataset.answer,id=q.dataset.quizId;q.querySelectorAll('.answer').forEach(x=>x.classList.remove('wrong'));if(chosen===correct){q.querySelectorAll('.answer').forEach(x=>x.disabled=true);b.classList.add('correct');q.querySelector('.feedback').textContent='Correct. '+q.dataset.why;if(!state.quizzes.includes(id)){state.quizzes.push(id);save();toast('+20 XP · Knowledge check cleared')}}else{b.classList.add('wrong');q.querySelector('.feedback').textContent='Not quite. '+q.dataset.why+' Try again.'}}
function renderStats(){const total=segments.reduce((n,s)=>n+s.lessons.length,0),done=state.complete.length,p=Math.round(done/total*100),xp=done*50+state.quizzes.length*20;$('#progressPercent').textContent=`${p}%`;$('#progressBar').style.width=`${p}%`;$('#xpValue').textContent=xp;const count=$('#courseLessonCount'),scope=$('#courseScope');if(count)count.textContent=total;if(scope)scope.textContent=`${segments.length} chapters · ${total} sections`}
function render(){renderRoadmap();renderTabs();renderLesson();renderStats()}
function move(delta){let s=state.segment,l=state.lesson+delta;if(l>=segments[s].lessons.length){if(s<segments.length-1){s++;l=0}else{completeCurrent();toast(`Segment ${segments.length} complete · Course finished`)}}if(l<0){if(s>0){s--;l=segments[s].lessons.length-1}else return}state.segment=s;state.lesson=l;save();render();$('#workspace').scrollIntoView({behavior:'smooth'})}
function completeCurrent(){const id=lessonId(),lesson=segments[state.segment].lessons[state.lesson];if(lesson.title==='Section knowledge check'){const required=$$('.quiz').length,passed=$$('.quiz').filter(q=>state.quizzes.includes(q.dataset.quizId)).length;if(passed<required){toast(`Pass all ${required} questions first · ${passed}/${required} correct`);return false}}if(!state.complete.includes(id)){state.complete.push(id);save();toast('+50 XP · Lesson complete')}render();return true}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
$('#completeLesson').onclick=()=>{const id=lessonId();if(state.complete.includes(id)){state.complete=state.complete.filter(x=>x!==id);save();render()}else completeCurrent()};
$('#nextLesson').onclick=()=>{if(completeCurrent())move(1)};$('#prevLesson').onclick=()=>move(-1);
$('#continueBtn').onclick=enterLessonMode;
$('#breadcrumbSegment').onclick=()=>{state.lesson=0;save();render()};
$('#curriculumToggle').onclick=()=>{const open=document.body.classList.toggle('nav-open');$('#curriculumToggle').setAttribute('aria-expanded',String(open))};
$('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');save()};
$('#resetProgress').onclick=()=>{if(confirm('Reset every lesson, quiz, and XP score?')){state.segment=0;state.lesson=0;state.complete=[];state.quizzes=[];save();render();toast('Course progress reset')}};
$('.brand').onclick=leaveLessonMode;
document.body.classList.toggle('dark',state.theme==='dark');
if(deepLink.has('segment')||deepLink.has('lesson'))document.body.classList.add('lesson-mode');
render();
